### ISSUE TITLE
Error running focus-last.py

### ISSUE THREAD

**Issue by yamsu** [acrisci/i3ipc-python#44]
Hi,

I'm interested to use the example file focus-last.py. I am executing it from the .xsessionrc file. However, It doesn't work. I'm using i3wm version 4.7.2

In my .xsessionrc, focus-last.py is executed
python3.4 focus-last.py

Get the following error from the .xsession-errors file:

Traceback (most recent call last):
  File "/home/dilbert/usr/bin/focus-last.py", line 91, in <module>
    focus_watcher = FocusWatcher()
  File "/home/dilbert/usr/bin/focus-last.py", line 17, in **init**
    self.i3 = i3ipc.Connection()
  File "/usr/local/lib/python3.4/dist-packages/i3ipc.py", line 181, in **init**
    if not data.value:
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by acrisci** [comment]
Hi,

The ipc changes between i3 versions which causes issues like this. 4.7.2 is currently not supported because this library was released after that version came out. If you can, update to 4.12 and it should work.

**Comment by yamsu** [comment]
Everything is working fine with 4.12 and later, thanks.
